server:  
  port: ${PORT:8761}
    
eureka:  
  instance:
    hostname:50.19.179.31
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false  
